# -*- coding: utf-8 -*-
"""
AWS 服务/产品英文名 → 练习模式中文标注。

练习模式：Spot Instances（竞价实例）
模拟考试：不调用本模块，保持纯英文题干与选项。
"""
from __future__ import annotations

import re
from typing import Iterable

# (英文术语, 中文简称) — 按英文长度降序，避免短词抢先匹配
_RAW_TERMS: list[tuple[str, str]] = [
    ("EC2 Instance Savings Plans", "EC2 实例节省计划"),
    ("Compute Savings Plans", "计算节省计划"),
    ("S3 Cross-Region Replication", "S3 跨区域复制"),
    ("S3 Transfer Acceleration", "S3 传输加速"),
    ("S3 Intelligent-Tiering", "S3 智能分层"),
    ("Reserved Instance Marketplace", "预留实例市场"),
    ("Personal Health Dashboard", "个人健康面板"),
    ("Well-Architected Framework", "架构良好框架"),
    ("Well-Architected Tool", "架构良好工具"),
    ("Shared Responsibility Model", "责任共担模型"),
    ("Technical Account Manager", "技术客户经理"),
    ("Service Control Policies", "服务控制策略"),
    ("Multi-Factor Authentication", "多因素认证"),
    ("Identity-based policy", "基于身份的策略"),
    ("Resource-based policy", "基于资源的策略"),
    ("Customer Managed Key", "客户托管密钥"),
    ("AWS Global Accelerator", "全球加速器"),
    ("AWS Network Firewall", "网络防火墙"),
    ("AWS Client VPN", "客户端 VPN"),
    ("Site-to-Site VPN", "站点到站点 VPN"),
    ("AWS Transit Gateway", "中转网关"),
    ("AWS Direct Connect", "专线连接"),
    ("AWS Control Tower", "控制塔"),
    ("AWS Service Catalog", "服务目录"),
    ("AWS CloudFormation", "基础设施即代码"),
    ("AWS Trusted Advisor", "可信顾问"),
    ("AWS Secrets Manager", "密钥管理器"),
    ("AWS Security Hub", "安全中心"),
    ("IAM Access Analyzer", "IAM 访问分析器"),
    ("Interface Endpoint", "接口端点"),
    ("Gateway Endpoint", "网关端点"),
    ("Internet Gateway", "互联网网关"),
    ("On-Demand Instances", "按需实例"),
    ("Reserved Instances", "预留实例"),
    ("Dedicated Instances", "专用实例"),
    ("Dedicated Hosts", "专用主机"),
    ("Placement Groups", "放置群组"),
    ("Availability Zone", "可用区"),
    ("Wavelength Zones", "波长区域"),
    ("Block Public Access", "阻止公开访问"),
    ("Envelope Encryption", "信封加密"),
    ("Elastic Block Store", "弹性块存储"),
    ("Elastic Beanstalk", "应用部署平台"),
    ("Cost Anomaly Detection", "成本异常检测"),
    ("Cost and Usage Report", "成本与使用报告"),
    ("Amazon CloudFront", "内容分发网络"),
    ("Amazon GuardDuty", "威胁检测"),
    ("Amazon EventBridge", "事件总线"),
    ("Amazon API Gateway", "API 网关"),
    ("Amazon QuickSight", "商业智能"),
    ("Amazon SageMaker", "机器学习平台"),
    ("Amazon DocumentDB", "文档数据库"),
    ("Amazon ElastiCache", "内存缓存"),
    ("Amazon CloudWatch", "监控服务"),
    ("Amazon Route 53", "DNS 服务"),
    ("Amazon Lightsail", "轻量服务器"),
    ("Amazon Keyspaces", "Cassandra 兼容库"),
    ("Amazon Timestream", "时序数据库"),
    ("Amazon Detective", "安全调查"),
    ("Amazon Macie", "敏感数据发现"),
    ("Amazon Neptune", "图数据库"),
    ("Amazon Redshift", "数据仓库"),
    ("Amazon DynamoDB", "NoSQL 数据库"),
    ("Amazon Athena", "即席查询"),
    ("AWS Marketplace", "云市场"),
    ("AWS Organizations", "组织管理"),
    ("AWS Step Functions", "工作流编排"),
    ("AWS Storage Gateway", "存储网关"),
    ("AWS Certificate Manager", "证书管理"),
    ("AWS Pricing Calculator", "定价计算器"),
    ("AWS Cost Explorer", "成本探索器"),
    ("AWS DataSync", "数据同步"),
    ("AWS Snowball", "离线迁移设备"),
    ("AWS Snow Family", "Snow 系列设备"),
    ("AWS App Runner", "应用运行器"),
    ("AWS CloudTrail", "API 审计"),
    ("AWS CloudHSM", "硬件安全模块"),
    ("AWS Amplify", "全栈开发平台"),
    ("AWS IoT Core", "物联网核心"),
    ("AWS Inspector", "漏洞扫描"),
    ("AWS Lambda", "无服务器函数"),
    ("AWS Outposts", "本地部署"),
    ("AWS WAF", "Web 应用防火墙"),
    ("AWS Shield", "DDoS 防护"),
    ("AWS Config", "配置合规"),
    ("AWS Signer", "代码签名"),
    ("AWS Glue", "ETL 服务"),
    ("AWS Fargate", "无服务器容器"),
    ("AWS Budgets", "预算管理"),
    ("AWS Free Tier", "免费套餐"),
    ("AWS Managed Key", "AWS 托管密钥"),
    ("AWS KMS", "密钥管理"),
    ("AWS IAM", "身份与访问管理"),
    ("Spot Instances", "竞价实例"),
    ("Spot Instance", "竞价实例"),
    ("Savings Plans", "节省计划"),
    ("Auto Scaling", "自动扩展"),
    ("Object Lock", "对象锁定"),
    ("Access Points", "访问点"),
    ("Local Zones", "本地区域"),
    ("Edge Locations", "边缘站点"),
    ("VPC Peering", "VPC 对等连接"),
    ("VPC Endpoint", "VPC 端点"),
    ("VPC Flow Logs", "VPC 流日志"),
    ("NAT Gateway", "NAT 网关"),
    ("Security Group", "安全组"),
    ("Network ACL", "网络 ACL"),
    ("Parameter Store", "参数存储"),
    ("Global Accelerator", "全球加速器"),
    ("Global service", "全球服务"),
    ("Nitro System", "Nitro 系统"),
    ("Multi-Region", "多区域"),
    ("Multi-AZ", "多可用区"),
    ("CloudFront", "内容分发"),
    ("CloudWatch", "监控"),
    ("CloudTrail", "审计日志"),
    ("CloudHSM", "硬件安全模块"),
    ("GuardDuty", "威胁检测"),
    ("EventBridge", "事件总线"),
    ("QuickSight", "BI 分析"),
    ("SageMaker", "机器学习"),
    ("DocumentDB", "文档数据库"),
    ("ElastiCache", "缓存服务"),
    ("Route 53", "DNS"),
    ("Lightsail", "轻量服务器"),
    ("Keyspaces", "宽列数据库"),
    ("Timestream", "时序数据库"),
    ("Detective", "安全调查"),
    ("Redshift", "数据仓库"),
    ("DynamoDB", "NoSQL"),
    ("Athena", "即席查询"),
    ("Organizations", "组织"),
    ("CloudFormation", "堆栈编排"),
    ("Service Catalog", "服务目录"),
    ("Control Tower", "控制塔"),
    ("Trusted Advisor", "可信顾问"),
    ("Secrets Manager", "密钥管理"),
    ("Security Hub", "安全中心"),
    ("Direct Connect", "专线"),
    ("Transit Gateway", "中转网关"),
    ("Client VPN", "客户端 VPN"),
    ("App Runner", "应用运行"),
    ("Step Functions", "工作流"),
    ("Storage Gateway", "存储网关"),
    ("Certificate Manager", "证书管理"),
    ("Cost Explorer", "成本分析"),
    ("DataSync", "数据同步"),
    ("Snowball", "离线迁移"),
    ("Amplify", "前端托管"),
    ("IoT Core", "物联网"),
    ("Inspector", "漏洞评估"),
    ("Outposts", "本地云"),
    ("Macie", "敏感数据"),
    ("Neptune", "图数据库"),
    ("Fargate", "无服务器容器"),
    ("Beanstalk", "应用平台"),
    ("Guardrails", "防护机制"),
    ("Marketplace", "云市场"),
    ("Versioning", "版本控制"),
    ("Cognito", "用户认证"),
    ("Artifact", "合规报告"),
    ("Signer", "代码签名"),
    ("Kinesis", "流数据"),
    ("PrivateLink", "私有连接"),
    ("Firewall Manager", "防火墙管理器"),
    ("Permission Boundary", "权限边界"),
    ("AssumeRole", "承担角色"),
    ("IAM Role", "IAM 角色"),
    ("IAM User", "IAM 用户"),
    ("IAM Policy", "IAM 策略"),
    ("IAM Group", "IAM 用户组"),
    ("Amazon S3", "对象存储"),
    ("Amazon VPC", "虚拟私有云"),
    ("Amazon RDS", "关系型数据库"),
    ("Amazon Aurora", "云原生数据库"),
    ("Amazon EC2", "弹性计算"),
    ("Amazon ECS", "容器服务"),
    ("Amazon EKS", "Kubernetes"),
    ("Amazon EMR", "大数据"),
    ("Amazon EFS", "文件存储"),
    ("Amazon FSx", "文件系统"),
    ("Amazon EBS", "块存储"),
    ("Amazon MQ", "消息代理"),
    ("Amazon SQS", "消息队列"),
    ("Amazon SNS", "通知服务"),
    ("Amazon QLDB", "账本数据库"),
    ("Elastic File System", "弹性文件系统"),
    ("Reserved Instance", "预留实例"),
    ("Spot Fleet", "竞价舰队"),
    ("Warm Standby", "温备"),
    ("Pilot Light", "指示灯"),
    ("High Availability", "高可用"),
    ("Fault Tolerance", "容错"),
    ("Economies of Scale", "规模经济"),
    ("Loose Coupling", "松耦合"),
    ("Serverless", "无服务器"),
    ("Microservices", "微服务"),
    ("MFA", "多因素认证"),
    ("SCP", "服务控制策略"),
    ("CMK", "客户托管密钥"),
    ("SSE-KMS", "KMS 服务端加密"),
    ("SSE-S3", "S3 服务端加密"),
    ("SSE-C", "客户端提供密钥加密"),
    ("RI Marketplace", "预留实例市场"),
    ("TAM", "技术客户经理"),
    ("CUR", "成本使用报告"),
    # --- 高频缩写与短术语（CLF 题库审计补全）---
    ("AWS Database Migration Service", "数据库迁移服务"),
    ("Amazon Aurora Global Database", "Aurora 全球数据库"),
    ("Amazon Aurora Serverless", "Aurora 无服务器"),
    ("Amazon EC2 Auto Scaling Group", "EC2 自动扩展组"),
    ("Amazon Kinesis Data Streams", "Kinesis 数据流"),
    ("Amazon RDS Custom", "RDS 自定义"),
    ("Amazon S3 Transfer Acceleration", "S3 传输加速"),
    ("Application Load Balancer", "应用负载均衡器"),
    ("Auto Scaling Group", "自动扩展组"),
    ("AWS Billing Conductor", "账单编排"),
    ("AWS Cost Categories", "成本分类"),
    ("AWS Enterprise Support", "企业级支持"),
    ("AWS Identity and Access Management", "身份与访问管理"),
    ("AWS Resource Access Manager", "资源共享管理器"),
    ("AWS Shield Advanced", "Shield 高级版"),
    ("AWS Shield Standard", "Shield 标准版"),
    ("AWS Snowball Edge", "Snowball 边缘设备"),
    ("AWS Well-Architected Framework", "架构良好框架"),
    ("AWS Well-Architected Tool", "架构良好工具"),
    ("IAM Roles Anywhere", "IAM 任意位置角色"),

    ("Database Migration Service", "数据库迁移服务"),
    ("Elastic Load Balancing", "弹性负载均衡"),
    ("Elastic Network Interface", "弹性网络接口"),
    ("Glacier Deep Archive", "Glacier 深度归档"),
    ("Glacier Instant Retrieval", "Glacier 即时取回"),
    ("High Performance Computing", "高性能计算"),
    ("Horizontal Scaling", "水平扩展"),
    ("IAM Identity Center", "IAM 身份中心"),
    ("Partition Placement Group", "分区放置群组"),
    ("Spread Placement Group", "分散放置群组"),
    ("Transfer Acceleration", "传输加速"),
    ("Intelligent-Tiering", "智能分层"),
    ("Enterprise Support", "企业级支持"),
    ("Business Support", "商业级支持"),
    ("Developer Support", "开发者支持"),
    ("Basic Support", "基础支持"),
    ("Consolidated Billing", "合并账单"),
    ("Lifecycle Policies", "生命周期策略"),
    ("Lifecycle Policy", "生命周期策略"),
    ("Availability Zones", "可用区"),
    ("Edge Location", "边缘站点"),
    ("Instance Store", "实例存储"),
    ("Snowball Edge", "Snowball 边缘"),
    ("Storage Lens", "存储透镜"),
    ("Requester Pays", "请求者付费"),
    ("Landing Zone", "着陆区"),
    ("Account Factory", "账户工厂"),
    ("Roles Anywhere", "任意位置角色"),
    ("Billing Conductor", "账单编排"),
    ("Management Account", "管理账户"),
    ("Batch Operations", "批量操作"),
    ("Bucket Policy", "存储桶策略"),
    ("Object Ownership", "对象所有权"),
    ("Customer Managed Keys", "客户托管密钥"),
    ("Encrypted Data Key", "加密数据密钥"),
    ("Operational Excellence", "运营卓越"),
    ("Performance Efficiency", "性能效率"),
    ("Cost Optimization", "成本优化"),
    ("Cost Categories", "成本分类"),
    ("Identity Center", "身份中心"),
    ("Resource Access Manager", "资源共享管理器"),
    ("Systems Manager", "系统管理器"),
    ("Security Groups", "安全组"),
    ("Dedicated Host", "专用主机"),
    ("Placement Group", "放置群组"),
    ("Private Subnet", "私有子网"),
    ("Route Table", "路由表"),
    ("Route Tables", "路由表"),
    ("Config Rules", "配置规则"),
    ("Access Key", "访问密钥"),
    ("Secret Key", "秘密密钥"),
    ("Key Policy", "密钥策略"),
    ("Data Key", "数据密钥"),
    ("Root Account", "根账户"),
    ("Root User", "根用户"),
    ("Least Privilege", "最小权限"),
    ("Load Balancer", "负载均衡器"),
    ("File Gateway", "文件网关"),
    ("Volume Gateway", "卷网关"),
    ("Capacity Rebalancing", "容量再平衡"),
    ("Managed Blockchain", "托管区块链"),
    ("Infrequent Access", "不频繁访问"),
    ("Archive Instant Access", "归档即时访问"),
    ("Shield Advanced", "Shield 高级版"),
    ("Shield Standard", "Shield 标准版"),
    ("Event-Driven", "事件驱动"),
    ("Launch Constraints", "启动约束"),
    ("Template Constraints", "模板约束"),
    ("Site Active", "站点活跃"),
    ("Multi-Site", "多站点"),
    ("Cross-Region", "跨区域"),
    ("Always Free", "永久免费"),
    ("One Zone-IA", "单可用区低频访问"),
    ("Deep Archive", "深度归档"),
    ("Flow Logs", "流日志"),
    ("Well-Architected", "架构良好"),
    ("On-Demand", "按需"),
    ("Managed Key", "托管密钥"),
    ("Owned Key", "自有密钥"),
    ("AWS Owned Key", "AWS 自有密钥"),
    ("Access Analyzer", "访问分析器"),
    ("Scale Out", "横向扩展"),
    ("Scale Up", "纵向扩展"),
    ("Time Recovery", "恢复时间"),
    ("Latency Reduction", "延迟降低"),
    ("Apache Cassandra", "Apache Cassandra"),
    ("On-Ramp", "上云通道"),
    ("Ramp Support", "上云支持"),
    ("Website Endpoint", "网站端点"),
    ("Public Endpoint", "公有端点"),
    ("Private Endpoint", "私有端点"),
    ("Regional Endpoint", "区域端点"),
    ("Global Endpoint", "全局端点"),
    ("Allocation Strategy", "分配策略"),
    ("Nitro Hypervisor", "Nitro 虚拟机监控"),
    ("Driven Architecture", "驱动架构"),
    ("Artificial Intelligence", "人工智能"),
    ("PCI DSS", "支付卡行业数据安全标准"),
    ("Transit Gateway Endpoint", "中转网关端点"),
    ("Standard-IA", "标准低频访问"),
    ("One Zone", "单可用区"),
    ("Pricing Calculator", "定价计算器"),
    ("Network Firewall", "网络防火墙"),
    ("Snow Family", "Snow 系列设备"),
    ("AWS Region", "AWS 区域"),
    ("AWS Regions", "AWS 区域"),
    ("AWS Support", "AWS 支持"),
    ("AWS CLI", "命令行工具"),
    ("Free Tier", "免费套餐"),
    ("Usage Report", "使用报告"),
    ("MQ", "消息代理"),
    # 独立缩写（依赖前后边界，避免 Multi-AZ 等误标）
    ("HTTPS", "安全超文本传输"),
    ("HTTP", "超文本传输"),
    ("IAM", "身份与访问管理"),
    ("VPC", "虚拟私有云"),
    ("RDS", "关系型数据库"),
    ("KMS", "密钥管理"),
    ("EBS", "块存储"),
    ("EFS", "文件存储"),
    ("ECS", "容器服务"),
    ("EKS", "Kubernetes 服务"),
    ("SNS", "通知服务"),
    ("SQS", "消息队列"),
    ("DMS", "数据库迁移"),
    ("ACM", "证书管理"),
    ("WAF", "Web 防火墙"),
    ("NACL", "网络 ACL"),
    ("NAT", "网络地址转换"),
    ("DNS", "域名系统"),
    ("CDN", "内容分发网络"),
    ("SSE", "服务端加密"),
    ("ALB", "应用负载均衡"),
    ("ELB", "弹性负载均衡"),
    ("ENI", "弹性网卡"),
    ("VPN", "虚拟专用网络"),
    ("ACL", "访问控制列表"),
    ("HSM", "硬件安全模块"),
    ("QLDB", "量子账本"),
    ("EMR", "大数据处理"),
    ("NLB", "网络负载均衡"),
    ("SSM", "系统管理器"),
    ("AMI", "机器镜像"),
    ("SSO", "单点登录"),
    ("WORM", "一次写入多次读取"),
    ("OLAP", "联机分析处理"),
    ("OLTP", "联机事务处理"),
    ("PITR", "时间点恢复"),
    ("CSPM", "云安全态势管理"),
    ("FINRA", "美国金融业监管局"),
    ("FIPS", "联邦信息处理标准"),
    ("SPARQL", "图查询语言"),
    ("MQTT", "物联网消息协议"),
    ("CQL", "Cassandra 查询语言"),
    ("ACID", "原子性一致性隔离持久性"),
    ("YAML", "YAML 配置格式"),
    ("REST", "REST 架构"),
    ("NFS", "网络文件系统"),
    ("SMB", "服务器消息块"),
    ("GPU", "图形处理器"),
    ("DAX", "DynamoDB 加速器"),
    ("HPC", "高性能计算"),
    ("PII", "个人身份信息"),
    ("BAA", "商业伙伴协议"),
    ("NDA", "保密协议"),
    ("DSS", "数据安全标准"),
    ("XSS", "跨站脚本攻击"),
    ("SLA", "服务等级协议"),
    ("CRR", "跨区域复制"),
    ("RCU", "读取容量单位"),
    ("WCU", "写入容量单位"),
    ("ACU", "Aurora 容量单位"),
    ("AZ", "可用区"),
    ("RI", "预留实例"),
    ("RTO", "恢复时间目标"),
    ("RPO", "恢复点目标"),
    ("OU", "组织单元"),
    ("HA", "高可用"),
    ("DR", "灾难恢复"),
    ("SG", "安全组"),
    ("GA", "全球加速器"),
    ("SP", "节省计划"),
    ("CI", "持续集成"),
    ("CD", "持续交付"),
    ("TCP", "传输控制协议"),
    ("UDP", "用户数据报协议"),
]

TERM_ANNOTATIONS: list[tuple[str, str]] = sorted(
    _RAW_TERMS,
    key=lambda pair: len(pair[0]),
    reverse=True,
)

_ALL_ENGLISH: list[str] = [en for en, _ in TERM_ANNOTATIONS]


def _longer_term_suffix_block(en: str, all_terms: list[str]) -> str:
    """阻止短术语抢先匹配更长术语的前缀，如 On-Demand vs On-Demand Instances。"""
    en_lower = en.lower()
    blocks: list[str] = []
    for other in all_terms:
        if len(other) <= len(en):
            continue
        if not other.lower().startswith(en_lower):
            continue
        rest = other[len(en) :]
        if rest:
            blocks.append(re.escape(rest))
    if not blocks:
        return ""
    return "(?!" + "|".join(blocks) + ")"


def _compile_term_pattern(
    en: str, all_terms: list[str] | None = None,
) -> re.Pattern[str]:
    return re.compile(
        r"(?<![A-Za-z0-9-])"
        + re.escape(en)
        + _longer_term_suffix_block(en, all_terms or _ALL_ENGLISH)
        + r"(?![A-Za-z0-9-])"
        + r"(?!（)",
        re.IGNORECASE,
    )


TERM_PATTERNS: list[tuple[re.Pattern[str], str]] = [
    (_compile_term_pattern(en), zh) for en, zh in TERM_ANNOTATIONS
]


def annotate_text(text: str, terms: Iterable[tuple[str, str]] | None = None) -> str:
    """
    在练习模式显示文本中为 AWS 英文术语追加「中文」标注。
    已标注的术语不会重复处理。
    """
    if not text:
        return text

    if terms is not None:
        term_list = sorted(terms, key=lambda pair: len(pair[0]), reverse=True)
        all_en = [en for en, _ in term_list]
        patterns = [
            (_compile_term_pattern(en, all_en), zh) for en, zh in term_list
        ]
    else:
        patterns = TERM_PATTERNS

    result = text
    for pattern, zh in patterns:
        result = pattern.sub(lambda m: f"{m.group(0)}（{zh}）", result)

    return result