# -*- coding: utf-8 -*-
"""31 个关键词缺口对应的补题（19 单选 + 11 多选 = 30 题）。"""

NEW_SINGLE = [
    {
        "id": "S142",
        "question": "AWS 云模式中的 Economies of Scale（规模经济）主要体现在哪一点？",
        "options": [
            "A. AWS 通过大规模采购和运营基础设施，将单位成本分摊给海量客户，使中小企业也能以较低价格使用企业级服务",
            "B. 客户必须预先购买大量 Reserved Instances 才能享受任何折扣，否则只能按最高 On-Demand 费率计费",
            "C. 规模经济仅适用于 EC2 计算服务，对 S3、RDS 等存储和数据库服务没有成本优势",
            "D. AWS 的规模经济意味着所有客户在任意 Region 的服务单价完全相同，不受使用量影响",
        ],
        "correct_answers": ["A"],
        "explanation": "「AWS 通过大规模采购和运营基础设施，将单位成本分摊给海量客户，使中小企业也能以较低价格使用企业级服务」是正确的。\n\nEconomies of Scale（规模经济）是 AWS 核心云概念之一：AWS 在全球运营超大规模基础设施，单位成本随规模下降，客户无需自建数据中心即可享受更低单价和更丰富服务。\n\n其他选项分析：\n\n「客户必须预先购买大量 Reserved Instances 才能享受任何折扣」是错误的：规模经济体现在基础定价和按需模式本身，不仅限于 RI。\n\n「规模经济仅适用于 EC2 计算服务」是错误的：S3、RDS、Lambda 等均受益于 AWS 整体规模效应。\n\n「所有客户在任意 Region 的服务单价完全相同」是错误的：不同 Region 定价不同，规模经济不等于统一定价。\n\n**重点考点 / 关键词补充：**\n- Economies of Scale = 规模越大，单位成本越低\n- 客户无需巨额前期投入即可获得企业级能力\n- CLF 常考：云 vs 自建数据中心的成本优势来源",
        "domain": "Cloud Concepts",
    },
    {
        "id": "S143",
        "question": "在 AWS Well-Architected Framework 的六大支柱中，Security（安全性支柱）主要关注什么？",
        "options": [
            "A. Security pillar 强调通过身份验证、授权、加密、监控和事件响应来保护数据和系统",
            "B. Security pillar 主要关注通过 Auto Scaling 和负载均衡实现应用的水平扩展能力",
            "C. Security pillar 的核心是降低月度账单，通过 Reserved Instances 和 Savings Plans 优化成本",
            "D. Security pillar 专注于减少碳排放和能源消耗，推动数据中心使用可再生能源",
        ],
        "correct_answers": ["A"],
        "explanation": "「Security pillar 强调通过身份验证、授权、加密、监控和事件响应来保护数据和系统」是正确的。\n\nWell-Architected Framework 的 Security（安全性支柱）关注保护信息、系统和资产，同时通过技术手段和业务流程实现风险可控。\n\n其他选项分析：\n\n「通过 Auto Scaling 和负载均衡实现水平扩展」是错误的：这属于 Performance Efficiency 或 Reliability 范畴。\n\n「降低月度账单和优化成本」是错误的：这是 Cost Optimization 支柱的职责。\n\n「减少碳排放和能源消耗」是错误的：这是 Sustainability 支柱的关注点。\n\n**重点考点 / 关键词补充：**\n- 六大支柱：运营卓越、安全、可靠性、性能效率、成本优化、可持续性\n- Security pillar = 身份、权限、加密、检测、响应\n- 考试常考各支柱职责区分",
        "domain": "Cloud Concepts",
    },
    {
        "id": "S144",
        "question": "关于 IAM Policy 的 Identity-based policy 与 Resource-based policy，以下哪种说法最准确？",
        "options": [
            "A. Identity-based policy 附加到 IAM 用户/角色/组；Resource-based policy 附加到 S3 桶、KMS 密钥等资源本身",
            "B. Identity-based policy 只能由 AWS 托管创建，客户无法编写自定义 Resource-based policy",
            "C. Resource-based policy 仅适用于 EC2 实例，Identity-based policy 仅适用于 S3 存储桶",
            "D. 两种策略类型功能完全相同，只是命名不同，可以互换使用而不影响权限效果",
        ],
        "correct_answers": ["A"],
        "explanation": "「Identity-based policy 附加到 IAM 用户/角色/组；Resource-based policy 附加到 S3 桶、KMS 密钥等资源本身」是正确的。\n\nIdentity-based policy 定义「谁可以做什么」；Resource-based policy 定义「谁可以访问这个资源」（如 S3 桶策略、KMS 密钥策略）。\n\n其他选项分析：\n\n「Identity-based policy 只能由 AWS 托管创建」是错误的：客户可创建自定义 identity-based 和 resource-based 策略。\n\n「Resource-based policy 仅适用于 EC2」是错误的：常见于 S3、KMS、SNS、SQS 等。\n\n「两种策略功能完全相同可互换」是错误的：附加对象和适用场景不同。\n\n**重点考点 / 关键词补充：**\n- Identity-based：附在 principal（用户/角色/组）\n- Resource-based：附在 resource（桶策略、密钥策略）\n- 常考：跨账户 S3 访问常需 bucket policy（resource-based）",
        "domain": "Security and Compliance",
    },
    {
        "id": "S145",
        "question": "IAM Access Analyzer 的主要用途是什么？",
        "options": [
            "A. 分析账户中可被外部实体访问的资源，识别过度宽松的 resource-based policy 和公开暴露风险",
            "B. 自动轮换所有 KMS 客户托管密钥，并在密钥泄露时执行一键撤销操作",
            "C. 替代 AWS Config 持续记录所有 EC2 实例的配置变更历史并生成合规报告",
            "D. 实时监控 VPC 内所有子网的流量模式，自动阻断可疑的入站连接请求",
        ],
        "correct_answers": ["A"],
        "explanation": "「分析账户中可被外部实体访问的资源，识别过度宽松的 resource-based policy 和公开暴露风险」是正确的。\n\nIAM Access Analyzer 使用基于资源的策略分析，帮助发现 S3 桶、IAM 角色、KMS 密钥等是否被意外共享给外部账户或互联网。\n\n其他选项分析：\n\n「自动轮换所有 KMS 密钥」是错误的：密钥轮换是 KMS 功能，非 Access Analyzer 职责。\n\n「替代 AWS Config 记录配置变更」是错误的：Config 负责配置合规与变更历史。\n\n「实时监控 VPC 流量并阻断连接」是错误的：这是 Network Firewall、GuardDuty 等服务的范畴。\n\n**重点考点 / 关键词补充：**\n- Access Analyzer：发现外部可访问资源（外部访问 findings）\n- 常搭配 S3 Block Public Access 和最小权限原则\n- 免费服务，所有账户可用",
        "domain": "Security and Compliance",
    },
    {
        "id": "S146",
        "question": "何时应选择 AWS CloudHSM 而不是 AWS KMS？",
        "options": [
            "A. 需要完全控制硬件安全模块 (HSM)，满足严格的合规要求（如 FIPS 140-2 Level 3），且密钥材料不可被 AWS 访问",
            "B. 仅需对 S3 对象启用默认服务端加密 (SSE-S3)，使用 AWS 托管密钥即可满足一般数据保护需求",
            "C. 需要为 Lambda 和容器应用自动管理数据库连接字符串、API 密钥等凭据的轮换与安全检索",
            "D. 希望通过 AWS Organizations 和 IAM Identity Center 在单一控制台统一管理多账户用户与联合身份访问",
        ],
        "correct_answers": ["A"],
        "explanation": "「需要完全控制硬件安全模块 (HSM)，满足严格的合规要求，且密钥材料不可被 AWS 访问」是正确的。\n\nAWS CloudHSM 提供专用的 FIPS 140-2 Level 3 验证硬件安全模块，客户独占 HSM 实例，适合金融、政府等强合规场景。KMS 是共享多租户服务，由 AWS 管理底层 HSM。\n\n其他选项分析：\n\n「仅需对 S3 对象启用默认服务端加密 (SSE-S3)，使用 AWS 托管密钥即可满足一般数据保护需求」是错误的：SSE-S3 或 SSE-KMS 即可，无需 CloudHSM。\n\n「需要为 Lambda 和容器应用自动管理数据库连接字符串、API 密钥等凭据的轮换与安全检索」是错误的：应使用 Secrets Manager 或 Parameter Store。\n\n「希望通过 AWS Organizations 和 IAM Identity Center 在单一控制台统一管理多账户用户与联合身份访问」是错误的：这是 IAM 和 Organizations 的职责，与 HSM 选型无关。\n\n**重点考点 / 关键词补充：**\n- CloudHSM：单租户 HSM，客户完全控制密钥\n- KMS：多租户、易用、与大多数 AWS 服务集成\n- 可与 KMS 集成（Custom Key Store）使用 CloudHSM 支撑 CMK",
        "domain": "Security and Compliance",
    },
    {
        "id": "S147",
        "question": "AWS Network Firewall 主要用于解决什么问题？",
        "options": [
            "A. 在 VPC 边界或子网级别提供有状态的深度包检测、域名过滤和入侵防护，控制南北向和东西向流量",
            "B. 在应用层（HTTP/HTTPS）过滤恶意 Web 请求，防止 SQL 注入和跨站脚本攻击",
            "C. 自动扫描 EC2 实例操作系统漏洞并生成修复补丁部署计划",
            "D. 集中聚合 GuardDuty、Inspector 和 Macie 的安全发现，提供统一合规评分仪表盘",
        ],
        "correct_answers": ["A"],
        "explanation": "「在 VPC 边界或子网级别提供有状态的深度包检测、域名过滤和入侵防护，控制南北向和东西向流量」是正确的。\n\nAWS Network Firewall 是托管的网络防火墙服务，部署在 VPC 中，支持状态检测、Suricata 规则、域名列表等，保护整个 VPC 网络流量。\n\n其他选项分析：\n\n「在应用层过滤恶意 Web 请求」是错误的：这是 AWS WAF 的职责。\n\n「扫描 EC2 操作系统漏洞」是错误的：这是 Amazon Inspector 的功能。\n\n「聚合安全发现提供合规评分」是错误的：这是 AWS Security Hub 的职责。\n\n**重点考点 / 关键词补充：**\n- Network Firewall：L3-L4 网络层防火墙（VPC 级）\n- WAF：L7 Web 应用防火墙（CloudFront/ALB/API Gateway）\n- 常考：Network Firewall vs WAF vs Security Group 层级不同",
        "domain": "Security and Compliance",
    },
    {
        "id": "S148",
        "question": "Amazon Detective 的主要价值是什么？",
        "options": [
            "A. 将 GuardDuty 等安全服务的发现关联为可视化调查图，帮助分析安全事件的根本原因和影响范围",
            "B. 自动修复 S3 存储桶的公开访问配置，并阻止所有来自互联网的未授权下载请求",
            "C. 替代 CloudTrail 记录所有 API 调用，并提供无限期的免费日志存储",
            "D. 为开发团队提供代码仓库的静态分析和 CI/CD 流水线安全扫描",
        ],
        "correct_answers": ["A"],
        "explanation": "「将 GuardDuty 等安全服务的发现关联为可视化调查图，帮助分析安全事件的根本原因和影响范围」是正确的。\n\nAmazon Detective 使用机器学习分析 VPC Flow Logs、CloudTrail 和 GuardDuty 数据，构建实体关系图，加速安全事件调查，不负责主动检测或修复。\n\n其他选项分析：\n\n「自动修复 S3 公开访问」是错误的：Detective 是调查分析工具，不执行修复。\n\n「替代 CloudTrail 记录 API」是错误的：Detective 消费 CloudTrail 数据，不替代它。\n\n「代码仓库静态分析」是错误的：这是 Inspector、CodeGuru 等开发安全工具范畴。\n\n**重点考点 / 关键词补充：**\n- GuardDuty：检测威胁\n- Detective：调查分析（事后根因）\n- Security Hub：聚合与合规态势",
        "domain": "Security and Compliance",
    },
    {
        "id": "S149",
        "question": "AWS Signer 主要用于什么场景？",
        "options": [
            "A. 对容器镜像、Lambda 部署包等代码制品进行数字签名，确保部署时验证来源完整性和未被篡改",
            "B. 为公有网站自动申请和续期 SSL/TLS 证书，并绑定到 CloudFront 分发",
            "C. 管理 IAM 用户的 MFA 设备和硬件安全密钥注册信息",
            "D. 在 Organizations 中集中签署和审批所有 Service Control Policies 的变更请求",
        ],
        "correct_answers": ["A"],
        "explanation": "「对容器镜像、Lambda 部署包等代码制品进行数字签名，确保部署时验证来源完整性和未被篡改」是正确的。\n\nAWS Signer 提供代码签名功能，常与 ECR、Lambda、IoT 等设备固件分发配合，确保仅部署经过验证的签名制品。\n\n其他选项分析：\n\n「自动申请 SSL/TLS 证书」是错误的：这是 AWS Certificate Manager (ACM) 的职责。\n\n「管理 IAM MFA 设备」是错误的：MFA 在 IAM 控制台管理。\n\n「审批 SCP 变更」是错误的：SCP 在 Organizations 中管理，Signer 不涉政策审批。\n\n**重点考点 / 关键词补充：**\n- Signer = 代码/制品签名（supply chain 安全）\n- ACM = 证书管理（HTTPS）\n- 常考与容器安全、Lambda 部署完整性相关",
        "domain": "Security and Compliance",
    },
    {
        "id": "S150",
        "question": "AWS Nitro System 为 Amazon EC2 带来了哪些核心优势？",
        "options": [
            "A. 将虚拟化、网络、存储和安全功能卸载到专用 Nitro 硬件/card，提升性能、安全性和资源隔离",
            "B. 允许客户在 EC2 实例内直接运行未经 AWS 认证的第三方 Hypervisor 以替代 Nitro Hypervisor",
            "C. Nitro System 的主要目的是替代 Auto Scaling Group 实现跨 Region 的自动实例扩缩容",
            "D. Nitro System 是一种 EC2 购买选项，承诺 3 年使用量可获得比 Standard RI 更高的折扣",
        ],
        "correct_answers": ["A"],
        "explanation": "「将虚拟化、网络、存储和安全功能卸载到专用 Nitro 硬件/card，提升性能、安全性和资源隔离」是正确的。\n\nNitro System 是 AWS 自研的底层虚拟化架构，几乎覆盖所有现代 EC2 实例，带来更高网络带宽、更低延迟和更强租户隔离。\n\n其他选项分析：\n\n「运行第三方 Hypervisor 替代 Nitro」是错误的：客户无法替换底层 Nitro Hypervisor。\n\n「替代 Auto Scaling 实现扩缩容」是错误的：Auto Scaling 是上层编排服务。\n\n「一种 EC2 购买选项」是错误的：Nitro 是底层架构，不是计费模式。\n\n**重点考点 / 关键词补充：**\n- Nitro = 硬件加速虚拟化平台\n- 几乎所有新实例类型均基于 Nitro\n- 带来更高 ENI 性能和安全隔离",
        "domain": "Technology and Services",
    },
    {
        "id": "S151",
        "question": "AWS App Runner 最适合哪种应用场景？",
        "options": [
            "A. 快速部署和运行容器化 Web 应用或 API，无需管理底层基础设施，适合从源代码或容器镜像直接上线",
            "B. 编排复杂的多步骤 ETL 数据管道，并在 Spark 集群上执行大规模批处理作业",
            "C. 在本地数据中心与 AWS 之间建立专用网络专线，降低混合云连接的延迟和抖动",
            "D. 为机器学习团队提供 Jupyter Notebook 环境和 GPU 训练集群的托管服务",
        ],
        "correct_answers": ["A"],
        "explanation": "「快速部署和运行容器化 Web 应用或 API，无需管理底层基础设施，适合从源代码或容器镜像直接上线」是正确的。\n\nAWS App Runner 是完全托管的容器应用服务，自动处理构建、部署、扩缩容和负载均衡，定位介于 Elastic Beanstalk 和 ECS/Fargate 之间的简便方案。\n\n其他选项分析：\n\n「编排 ETL 和 Spark 批处理」是错误的：应使用 Glue、EMR 或 Step Functions。\n\n「建立专用网络专线」是错误的：应使用 Direct Connect 或 Site-to-Site VPN。\n\n「Jupyter 和 GPU 训练」是错误的：应使用 SageMaker。\n\n**重点考点 / 关键词补充：**\n- App Runner：最简单容器 Web 部署路径之一\n- 支持 GitHub/CodeCommit 自动 CI/CD\n- vs ECS/Fargate：App Runner 更偏「零运维」",
        "domain": "Technology and Services",
    },
    {
        "id": "S152",
        "question": "Amazon Neptune 主要用于什么类型的工作负载？",
        "options": [
            "A. 存储和查询高度关联的数据（如图谱关系网络），支持 Gremlin 和 SPARQL 等图查询语言",
            "B. 存储海量时序指标数据（如 IoT 传感器读数），并针对时间范围查询进行优化",
            "C. 提供兼容 Cassandra 的宽列 NoSQL 数据库，适合高写入吞吐的键值访问模式",
            "D. 提供不可篡改的集中式账本，使用量子抗性加密记录所有交易变更历史",
        ],
        "correct_answers": ["A"],
        "explanation": "「存储和查询高度关联的数据（如图谱关系网络），支持 Gremlin 和 SPARQL 等图查询语言」是正确的。\n\nAmazon Neptune 是全托管图数据库，适合社交网络、欺诈检测、知识图谱、推荐系统等需要遍历复杂关系的场景。\n\n其他选项分析：\n\n「存储时序指标数据」是错误的：应使用 Amazon Timestream。\n\n「兼容 Cassandra 的宽列数据库」是错误的：应使用 Amazon Keyspaces。\n\n「不可篡改的集中式账本」是错误的：应使用 Amazon QLDB。\n\n**重点考点 / 关键词补充：**\n- Neptune = 图数据库（关系遍历）\n- 与 DynamoDB（键值/文档）定位不同\n- 常考：社交网络、欺诈图谱 → Neptune",
        "domain": "Technology and Services",
    },
    {
        "id": "S153",
        "question": "Amazon Timestream 最适合哪种数据场景？",
        "options": [
            "A. 存储和分析大规模时序数据（如 IoT 传感器、运维指标），针对时间序列查询自动分层存储",
            "B. 运行复杂的关系型 SQL 联表查询，并支持 Multi-AZ 高可用的 OLTP 事务处理",
            "C. 托管 Apache Cassandra 工作负载，提供无服务器兼容 CQL 的宽列存储",
            "D. 构建社交网络中的好友关系图谱，并支持 Gremlin 图遍历查询",
        ],
        "correct_answers": ["A"],
        "explanation": "「存储和分析大规模时序数据（如 IoT 传感器、运维指标），针对时间序列查询自动分层存储」是正确的。\n\nAmazon Timestream 是专为时序数据设计的无服务器数据库，自动管理数据保留、压缩和冷热分层，适合 IoT 和运维监控场景。\n\n其他选项分析：\n\n「OLTP 关系型 SQL 联表」是错误的：应使用 RDS/Aurora。\n\n「托管 Cassandra 宽列存储」是错误的：应使用 Amazon Keyspaces。\n\n「图遍历查询」是错误的：应使用 Amazon Neptune。\n\n**重点考点 / 关键词补充：**\n- Timestream = 时序数据库\n- 自动保留策略 + 低成本历史数据分析\n- 常与 IoT Core、Kinesis 数据流配合",
        "domain": "Technology and Services",
    },
    {
        "id": "S154",
        "question": "Amazon Keyspaces 的主要定位是什么？",
        "options": [
            "A. 提供兼容 Apache Cassandra 的无服务器宽列数据库，适合高可用、高写入吞吐的应用",
            "B. 提供完全托管的图数据库，支持 Gremlin 和 SPARQL 查询语言遍历关系网络",
            "C. 提供专为时序 IoT 数据优化的数据库，内置时间范围聚合和自动数据过期策略",
            "D. 提供基于量子抗性加密的不可变账本数据库，记录所有金融交易变更",
        ],
        "correct_answers": ["A"],
        "explanation": "「提供兼容 Apache Cassandra 的无服务器宽列数据库，适合高可用、高写入吞吐的应用」是正确的。\n\nAmazon Keyspaces（for Apache Cassandra）让客户无需管理 Cassandra 集群，使用 CQL 接口，适合需要 Cassandra 兼容性的大规模分布式应用。\n\n其他选项分析：\n\n「图数据库 Gremlin/SPARQL」是错误的：应使用 Neptune。\n\n「时序 IoT 数据库」是错误的：应使用 Timestream。\n\n「不可变账本 QLDB」是错误的：应使用 Amazon QLDB。\n\n**重点考点 / 关键词补充：**\n- Keyspaces = Cassandra 兼容、无服务器\n- vs DynamoDB：Keyspaces 保持 CQL 和 Cassandra 数据模型\n- 适合迁移自托管 Cassandra 的场景",
        "domain": "Technology and Services",
    },
    {
        "id": "S155",
        "question": "Amazon QLDB（Quantum Ledger Database）的核心特性是什么？",
        "options": [
            "A. 提供中心化、不可篡改的账本，使用加密哈希链验证数据完整性和变更历史，适合审计和合规记录",
            "B. 提供去中心化的区块链网络，支持智能合约和加密货币挖矿验证机制",
            "C. 提供兼容 MySQL 的关系型数据库，并自动扩展存储至 128TB",
            "D. 提供专为实时 OLAP 分析优化的 PB 级数据仓库，适合 BI 报表查询",
        ],
        "correct_answers": ["A"],
        "explanation": "「提供中心化、不可篡改的账本，使用加密哈希链验证数据完整性和变更历史，适合审计和合规记录」是正确的。\n\nQLDB 是托管账本数据库，记录每笔交易的完整历史，提供可验证的审计追踪，不同于去中心化区块链（如 Managed Blockchain）。\n\n其他选项分析：\n\n「去中心化区块链和智能合约」是错误的：QLDB 是中心化账本；区块链场景用 Managed Blockchain。\n\n「兼容 MySQL 关系型数据库」是错误的：应使用 RDS/Aurora。\n\n「PB 级 OLAP 数据仓库」是错误的：应使用 Redshift。\n\n**重点考点 / 关键词补充：**\n- QLDB = 中心化可验证账本（非区块链）\n- 适合财务记录、供应链审计\n- 与 Object Lock WORM 场景有互补但定位不同",
        "domain": "Technology and Services",
    },
    {
        "id": "S156",
        "question": "AWS Client VPN 主要用于什么场景？",
        "options": [
            "A. 允许远程员工通过 OpenVPN 客户端安全接入 AWS VPC 或本地网络，实现灵活的远程访问",
            "B. 在两个 VPC 之间建立私有对等连接，使双方资源可通过私有 IP 直接通信",
            "C. 在本地数据中心与 AWS 之间建立专用物理专线，提供稳定的高带宽混合云连接",
            "D. 为全球用户提供 Anycast IP 加速 TCP/UDP 流量，降低跨区域游戏服务器延迟",
        ],
        "correct_answers": ["A"],
        "explanation": "「允许远程员工通过 OpenVPN 客户端安全接入 AWS VPC 或本地网络，实现灵活的远程访问」是正确的。\n\nAWS Client VPN 是托管的客户端 VPN 服务，支持员工从任意位置安全访问 VPC 内资源，可与 Active Directory 集成。\n\n其他选项分析：\n\n「两个 VPC 之间私有对等连接」是错误的：应使用 VPC Peering 或 Transit Gateway。\n\n「本地与 AWS 专用物理专线」是错误的：应使用 AWS Direct Connect。\n\n「Anycast IP 加速全球流量」是错误的：应使用 AWS Global Accelerator。\n\n**重点考点 / 关键词补充：**\n- Client VPN：远程用户 → VPC（OpenVPN）\n- Site-to-Site VPN：本地网关 ↔ AWS VPN（站点对站点）\n- Direct Connect：专用物理线路",
        "domain": "Technology and Services",
    },
    {
        "id": "S157",
        "question": "AWS Amplify 主要为哪类用户和场景设计？",
        "options": [
            "A. 帮助前端和移动开发者快速构建、部署和扩展全栈 Web/移动应用，集成认证、API 和托管",
            "B. 为数据工程师提供可视化 ETL 工具，将 S3 数据加载到 Redshift 数据仓库",
            "C. 为安全团队集中聚合 GuardDuty 和 Inspector 发现，生成合规态势报告",
            "D. 为运维团队提供跨账户的 EC2 实例补丁管理和远程 Shell 访问能力",
        ],
        "correct_answers": ["A"],
        "explanation": "「帮助前端和移动开发者快速构建、部署和扩展全栈 Web/移动应用，集成认证、API 和托管」是正确的。\n\nAWS Amplify 提供框架、CLI 和托管服务，简化 React/Vue/Angular 等前端与 Cognito、AppSync、S3 后端的集成与 CI/CD 部署。\n\n其他选项分析：\n\n「可视化 ETL 加载 Redshift」是错误的：应使用 AWS Glue。\n\n「聚合安全发现」是错误的：应使用 Security Hub。\n\n「EC2 补丁管理」是错误的：应使用 Systems Manager Patch Manager。\n\n**重点考点 / 关键词补充：**\n- Amplify = 前端/移动全栈开发加速\n- 常与 Cognito、AppSync、Lambda 配合\n- vs Elastic Beanstalk：Amplify 更偏前端工作流",
        "domain": "Technology and Services",
    },
    {
        "id": "S158",
        "question": "AWS IoT Core 的核心功能是什么？",
        "options": [
            "A. 作为物联网设备与 AWS 云服务之间的消息代理，支持 MQTT/HTTP 协议连接、规则引擎和数据路由",
            "B. 为时序传感器数据提供专用的 SQL 分析引擎和自动冷热分层存储服务",
            "C. 在 VPC 边界提供深度包检测防火墙，过滤来自 IoT 设备的恶意网络流量",
            "D. 为容器化微服务提供 Kubernetes 集群编排和 Pod 自动扩缩容能力",
        ],
        "correct_answers": ["A"],
        "explanation": "「作为物联网设备与 AWS 云服务之间的消息代理，支持 MQTT/HTTP 协议连接、规则引擎和数据路由」是正确的。\n\nAWS IoT Core 让数十亿设备安全连接云端，支持设备影子、规则引擎将数据转发到 Lambda、Kinesis、Timestream 等下游服务。\n\n其他选项分析：\n\n「时序数据 SQL 分析引擎」是错误的：时序存储用 Timestream，IoT Core 负责连接和路由。\n\n「VPC 深度包检测防火墙」是错误的：应使用 Network Firewall。\n\n「Kubernetes 集群编排」是错误的：应使用 Amazon EKS。\n\n**重点考点 / 关键词补充：**\n- IoT Core = 设备连接 + 消息路由\n- 常与 IoT Greengrass（边缘）、Timestream（存储）配合\n- 支持 MQTT（IoT 标准协议）",
        "domain": "Technology and Services",
    },
    {
        "id": "S159",
        "question": "关于 AWS Direct Connect 的定价特点，以下哪种说法最准确？",
        "options": [
            "A. Direct Connect pricing 通常包含端口小时费和数据传输费，相比公网 VPN 在大量稳定流量时可能更经济",
            "B. Direct Connect pricing 对所有客户完全免费，AWS 仅收取关联 VPC 的 NAT Gateway 处理费用",
            "C. Direct Connect pricing 仅按传输字节计费，端口容量和连接数量均不额外收费",
            "D. Direct Connect pricing 与 CloudFront 完全相同，按全球边缘节点请求次数和出站流量计费",
        ],
        "correct_answers": ["A"],
        "explanation": "「Direct Connect pricing 通常包含端口小时费和数据传输费，相比公网 VPN 在大量稳定流量时可能更经济」是正确的。\n\nAWS Direct Connect 提供专用网络连接，定价包含端口容量（按小时）和数据传输（出站通常收费，入站通常免费），适合持续大流量混合云场景。\n\n其他选项分析：\n\n「对所有客户完全免费」是错误的：Direct Connect 是付费专用连接服务。\n\n「仅按传输字节计费，端口不收费」是错误的：端口小时费是主要成本组成之一。\n\n「与 CloudFront 计费相同」是错误的：CloudFront 是 CDN 按请求和流量计费，模式完全不同。\n\n**重点考点 / 关键词补充：**\n- Direct Connect pricing：端口费 + 数据传输费\n- 大量稳定流量时可能比 VPN+公网更划算\n- 需配合 Virtual Interface 接入 VPC",
        "domain": "Billing, Pricing, and Support",
    },
    {
        "id": "S160",
        "question": "使用 Amazon S3 Transfer Acceleration 时，客户应如何理解其成本影响？",
        "options": [
            "A. Transfer Acceleration 成本包含加速数据传输费用，通常高于标准 S3 传输，但可显著缩短远距离上传时间",
            "B. Transfer Acceleration 成本对所有 AWS 账户完全免费，且不产生任何额外的数据传输费用",
            "C. Transfer Acceleration 成本仅收取一次性开通费，之后所有上传和下载流量均按 S3 标准费率计费",
            "D. Transfer Acceleration 成本与 AWS Direct Connect 端口小时费合并计费，无法单独查看",
        ],
        "correct_answers": ["A"],
        "explanation": "「Transfer Acceleration 成本包含加速数据传输费用，通常高于标准 S3 传输，但可显著缩短远距离上传时间」是正确的。\n\nS3 Transfer Acceleration 通过 CloudFront 边缘网络加速上传，会产生额外的加速数据传输费用（按 GB 计费），适合跨洋远距离上传场景。\n\n其他选项分析：\n\n「完全免费无额外费用」是错误的：加速传输有溢价费率。\n\n「仅一次性开通费」是错误的：按实际加速传输量持续计费。\n\n「与 Direct Connect 端口费合并」是错误的：两者是完全独立的计费项。\n\n**重点考点 / 关键词补充：**\n- Transfer Acceleration 成本 = 标准 S3 费用 + 加速溢价\n- 适合远距离、高延迟链路的上传优化\n- 可用 speed comparison 工具评估是否值得启用",
        "domain": "Billing, Pricing, and Support",
    },
]

NEW_MULTI = [
    {
        "id": "M110",
        "question": "关于 Local Zones vs Edge Locations vs Wavelength Zones 的区别，以下哪些说法是正确的？（选择三项）",
        "options": [
            "A. Local Zones 靠近人口中心，可运行较完整的 AWS 计算和存储服务，降低延迟",
            "B. Edge Locations 主要用于 CloudFront 等内容分发和缓存，不运行通用 EC2 工作负载",
            "C. Wavelength Zones 部署在 5G 运营商边缘，适合超低延迟的移动和实时应用",
            "D. 三者完全相同，均可运行与 Region 内相同范围的全套 AWS 托管服务",
        ],
        "correct_answers": ["A", "B", "C"],
        "explanation": "正确答案：\n\n「Local Zones 靠近人口中心，可运行较完整的 AWS 计算和存储服务」\n「Edge Locations 主要用于 CloudFront 等内容分发和缓存」\n「Wavelength Zones 部署在 5G 运营商边缘，适合超低延迟的移动和实时应用」\n\n本题考察 Local Zones vs Edge Locations vs Wavelength Zones 三者定位差异：Local Zones 补 Region 延迟；Edge Locations 做 CDN；Wavelength 做 5G 边缘计算。\n\n错误选项分析：\n\n「三者完全相同，均可运行与 Region 内相同范围的全套 AWS 托管服务」是错误的：只有 Local Zones 和 Wavelength 可运行较完整计算服务，Edge Locations 主要用于分发。\n\n**重点考点 / 关键词补充：**\n- Local Zones vs Edge Location vs Wavelength：CLF 高频对比\n- Edge Location = CDN 节点；Local Zone = 延伸 Region；Wavelength = 5G 边缘",
        "domain": "Cloud Concepts",
    },
    {
        "id": "M111",
        "question": "以下哪些 AWS 服务属于 Global service（全球服务）而非 Region level service？（选择两项）",
        "options": [
            "A. AWS Identity and Access Management (IAM) — 全球身份与访问管理服务，属于 Global service",
            "B. Amazon Route 53 — 全球 DNS 和域名注册服务，属于 Global service",
            "C. Amazon EC2 — 在特定 AWS Region 内创建的弹性计算实例，属于 Region level service",
            "D. Amazon RDS — 在选定 Region 内部署的托管关系型数据库，属于 Region level service",
        ],
        "correct_answers": ["A", "B"],
        "explanation": "正确答案：\n\n「AWS Identity and Access Management (IAM) — 全球身份与访问管理服务」\n「Amazon Route 53 — 全球 DNS 和域名注册服务」\n\nIAM 和 Route 53 是 Global service，在全球统一端点管理，不绑定特定 Region。EC2 和 RDS 是 Region level service，资源创建在特定 Region 内。\n\n错误选项分析：\n\n「Amazon EC2 — 在特定 AWS Region 内创建的弹性计算实例，属于 Region level service」是错误的：EC2 是 Region level service，不符合本题 Global service 要求。\n\n「Amazon RDS — 在选定 Region 内部署的托管关系型数据库，属于 Region level service」是错误的：RDS 数据库实例属于 Region level service。\n\n**重点考点 / 关键词补充：**\n- Global service 示例：IAM、Route 53、CloudFront、WAF（部分）\n- Region level service 示例：EC2、RDS、S3（桶绑定 Region）\n- 考试常考：IAM 全球唯一，策略全球生效",
        "domain": "Cloud Concepts",
    },
    {
        "id": "M112",
        "question": "关于 IAM Role vs IAM User 的最佳实践，以下哪些说法是正确的？（选择两项）",
        "options": [
            "A. 应用程序和 EC2 实例应使用 IAM Role 获取临时凭证，而非创建 IAM User 并硬编码 Access Key",
            "B. IAM User 适合需要长期控制台登录密码和 Access Key 的人类员工账户",
            "C. IAM Role 只能附加到 Root 用户，普通 IAM User 无法承担任何 Role",
            "D. IAM Role vs IAM User 没有区别，两者都可以安全地硬编码在应用程序源代码中",
        ],
        "correct_answers": ["A", "B"],
        "explanation": "正确答案：\n\n「应用程序和 EC2 实例应使用 IAM Role 获取临时凭证」\n「IAM User 适合需要长期控制台登录密码和 Access Key 的人类员工账户」\n\nIAM Role vs IAM User 是 CLF 最高频考点：工作负载用 Role（临时凭证），人员用 User。\n\n错误选项分析：\n\n「IAM Role 只能附加到 Root 用户」是错误的：Role 可附加到 EC2、Lambda、用户（承担角色）等。\n\n「两者没有区别可硬编码」是错误的：绝不应硬编码凭证，应用必须用 Role。\n\n**重点考点 / 关键词补充：**\n- IAM role vs user：机器/服务 → Role；人员 → User\n- AssumeRole 返回临时安全凭证\n- 最小权限 + 避免长期 Access Key",
        "domain": "Security and Compliance",
    },
    {
        "id": "M113",
        "question": "关于 KMS 中 CMK vs AWS Managed Key 的区别，以下哪些说法是正确的？（选择两项）",
        "options": [
            "A. Customer Managed Key (CMK) 由客户完全控制密钥策略、轮换和删除",
            "B. AWS Managed Key 由 AWS 创建和管理，客户无法删除或修改其密钥策略",
            "C. CMK vs AWS Managed Key 完全相同，客户对两者均有完全相同的删除和策略控制权",
            "D. AWS Managed Key 必须在 CloudHSM 集群中自行部署和维护硬件安全模块",
        ],
        "correct_answers": ["A", "B"],
        "explanation": "正确答案：\n\n「Customer Managed Key (CMK) 由客户完全控制密钥策略、轮换和删除」\n「AWS Managed Key 由 AWS 创建和管理，客户无法删除或修改其密钥策略」\n\nCMK vs AWS Managed Key 是加密考点核心：需要完全控制选 CMK，一般场景可用 AWS Managed Key。\n\n错误选项分析：\n\n「两者完全相同」是错误的：控制粒度差异显著。\n\n「AWS Managed Key 必须在 CloudHSM 中自行部署」是错误的：AWS Managed Key 由 AWS 多租户 KMS 管理，无需客户运维 HSM。\n\n**重点考点 / 关键词补充：**\n- CMK vs aws managed：控制度 vs 简便性\n- 合规场景常要求 CMK\n- AWS Owned Key 客户不可见",
        "domain": "Security and Compliance",
    },
    {
        "id": "M114",
        "question": "关于 Security Group vs NACL 的区别，以下哪些说法是正确的？（选择两项）",
        "options": [
            "A. Security Group 是有状态的，返回流量自动允许；NACL 是无状态的，需显式配置入站和出站规则",
            "B. Security Group 在实例级别生效；NACL 在子网级别生效",
            "C. Security Group vs NACL 完全相同，均在 Region 级别统一管理所有 VPC 流量",
            "D. NACL 是有状态的防火墙，Security Group 是无状态的子网级访问控制列表",
        ],
        "correct_answers": ["A", "B"],
        "explanation": "正确答案：\n\n「Security Group 是有状态的；NACL 是无状态的」\n「Security Group 在实例级别生效；NACL 在子网级别生效」\n\nSecurity Group vs NACL（安全组 vs nacl）是网络安全最高频对比。\n\n错误选项分析：\n\n「两者完全相同，均在 Region 级别管理」是错误的：作用层级和状态性完全不同。\n\n「NACL 有状态、SG 无状态」是错误的：描述完全颠倒。\n\n**重点考点 / 关键词补充：**\n- 安全组 vs nacl：实例级有状态 vs 子网级无状态\n- 可同时使用：SG 做默认防护，NACL 做额外子网边界\n- 返回流量：SG 自动允许，NACL 需显式规则",
        "domain": "Security and Compliance",
    },
    {
        "id": "M115",
        "question": "关于 S3 Object Lock 的 Compliance mode vs Governance mode，以下哪些说法是正确的？（选择两项）",
        "options": [
            "A. Compliance mode 下，包括 root 用户在内的任何主体在保留期内都无法删除或覆盖对象",
            "B. Governance mode 下，拥有特定权限的用户可以绕过保留设置删除或覆盖对象",
            "C. Compliance mode vs Governance mode 没有区别，两者都允许 root 用户随时删除锁定对象",
            "D. Governance mode 比 Compliance mode 更严格，任何用户包括 root 均无法绕过保留期",
        ],
        "correct_answers": ["A", "B"],
        "explanation": "正确答案：\n\n「Compliance mode 下任何主体在保留期内都无法删除或覆盖对象」\n「Governance mode 下拥有特定权限的用户可以绕过保留设置」\n\nCompliance mode vs Governance mode 是 Object Lock 核心对比：Compliance 最严格（监管合规），Governance 允许特权用户治理。\n\n错误选项分析：\n\n「两者没有区别，root 可随时删除」是错误的：Compliance mode 连 root 也无法绕过。\n\n「Governance mode 更严格」是错误的：Compliance mode 才是最严格的 governance mode。\n\n**重点考点 / 关键词补充：**\n- compliance mode / governance mode：WORM 两种模式\n- 需先开启 Versioning 才能启用 Object Lock\n- 金融/医疗合规常选 Compliance mode",
        "domain": "Technology and Services",
    },
    {
        "id": "M116",
        "question": "关于 Savings Plans vs Reserved Instances 的对比，以下哪些说法是正确的？（选择两项）",
        "options": [
            "A. Savings Plans 提供跨实例族、跨服务的灵活折扣承诺，而 Standard RI 通常锁定特定实例类型",
            "B. Reserved Instances 在特定实例类型上可能提供比 Compute Savings Plans 更高的折扣率",
            "C. Savings Plans vs Reserved Instances 完全相同，两者均只能用于 EC2 且必须锁定 m5 实例族",
            "D. Reserved Instances 可以随时取消并按比例获得全额退款，与 Savings Plans 一样灵活",
        ],
        "correct_answers": ["A", "B"],
        "explanation": "正确答案：\n\n「Savings Plans 提供跨实例族、跨服务的灵活折扣承诺」\n「Reserved Instances 在特定实例类型上可能提供比 Compute Savings Plans 更高的折扣率」\n\n节省计划 vs 预留实例是计费高频对比：SP 灵活，RI 折扣可能更高但锁定更强。\n\n错误选项分析：\n\n「两者完全相同且只能用于 m5」是错误的：SP 可覆盖 EC2/Fargate/Lambda。\n\n「RI 可随时取消全额退款」是错误的：RI 和 SP 都是承诺合约，通常不可随意取消。\n\n**重点考点 / 关键词补充：**\n- savings plans vs reserved：灵活性 vs 深度折扣\n- Compute SP 灵活性最高\n- Standard RI 折扣通常高于 SP 但锁定实例族",
        "domain": "Billing, Pricing, and Support",
    },
    {
        "id": "M117",
        "question": "关于 S3 vs EBS vs EFS vs FSx 的适用场景，以下哪些配对是正确的？（选择两项）",
        "options": [
            "A. S3：海量非结构化对象存储，通过 HTTP API 访问；EBS：挂载到单个 EC2 实例的块存储",
            "B. EFS：多 EC2 实例共享的 NFS 文件系统；FSx：托管 Windows/Lustre 等专用文件系统",
            "C. S3 vs EBS 完全相同，两者均为挂载到 EC2 的块级存储卷",
            "D. EFS 仅支持单台 EC2 挂载，与 EBS 一样无法被多台实例同时共享访问",
        ],
        "correct_answers": ["A", "B"],
        "explanation": "正确答案：\n\n「S3 对象存储 + EBS 块存储」\n「EFS 共享 NFS + FSx 专用文件系统」\n\nS3 vs EBS vs EFS vs FSx 是存储服务核心对比题。\n\n错误选项分析：\n\n「S3 vs EBS 完全相同均为块存储」是错误的：S3 是对象存储，EBS 是块存储。\n\n「EFS 仅支持单台 EC2 挂载」是错误的：EFS 专为多实例共享设计。\n\n**重点考点 / 关键词补充：**\n- S3 vs ebs：对象 vs 块\n- S3 vs efs：对象 vs 共享文件\n- FSx：Windows File Server / Lustre 专用场景",
        "domain": "Technology and Services",
    },
    {
        "id": "M118",
        "question": "关于 CloudFront vs Global Accelerator 的对比，以下哪些说法是正确的？（选择两项）",
        "options": [
            "A. CloudFront 主要优化 HTTP/HTTPS 内容分发和边缘缓存，适合静态和动态 Web 内容",
            "B. Global Accelerator 使用 Anycast IP 和 AWS 全球骨干网加速 TCP/UDP 流量，适合非 HTTP 协议",
            "C. CloudFront vs Global Accelerator 完全相同，两者均只能加速 HTTPS 网站内容",
            "D. Global Accelerator 主要通过边缘缓存静态文件降低延迟，不提供 Anycast IP 功能",
        ],
        "correct_answers": ["A", "B"],
        "explanation": "正确答案：\n\n「CloudFront 优化 HTTP/HTTPS 内容分发和边缘缓存」\n「Global Accelerator 加速 TCP/UDP 流量，适合非 HTTP 协议」\n\nCloudFront vs Global Accelerator 是网络加速核心对比。\n\n错误选项分析：\n\n「两者完全相同且只能加速 HTTPS」是错误的：GA 支持 TCP/UDP（游戏、VoIP）。\n\n「GA 主要通过边缘缓存静态文件」是错误的：缓存是 CloudFront 核心能力。\n\n**重点考点 / 关键词补充：**\n- CloudFront = CDN + HTTP/HTTPS\n- Global Accelerator = Anycast + TCP/UDP + 骨干网\n- 可组合使用：GA 加速入口 + CloudFront 缓存内容",
        "domain": "Technology and Services",
    },
    {
        "id": "M119",
        "question": "关于 GuardDuty vs Inspector vs Macie vs Security Hub 的职责，以下哪些配对是正确的？（选择两项）",
        "options": [
            "A. GuardDuty：基于 VPC Flow Logs 和 CloudTrail 检测恶意活动和异常行为",
            "B. Inspector：评估 EC2 实例和容器镜像的操作系统与应用程序漏洞",
            "C. GuardDuty vs Inspector 功能完全相同，两者均只扫描 S3 桶中的敏感 PII 数据",
            "D. Macie 替代 Security Hub 集中管理所有 IAM 用户权限和 SCP 策略",
        ],
        "correct_answers": ["A", "B"],
        "explanation": "正确答案：\n\n「GuardDuty 检测恶意活动和异常行为」\n「Inspector 评估操作系统和应用程序漏洞」\n\n（Macie 发现 S3 敏感数据；Security Hub 聚合安全发现。）\n\nGuardDuty vs Inspector 是安全服务易混淆考点。\n\n错误选项分析：\n\n「GuardDuty vs Inspector 完全相同且只扫描 S3 PII」是错误的：GuardDuty 做威胁检测，Inspector 做漏洞评估，Macie 做敏感数据发现。\n\n「Macie 替代 Security Hub 管理 IAM」是错误的：Macie 专注 S3 敏感数据；Security Hub 聚合安全态势。\n\n**重点考点 / 关键词补充：**\n- GuardDuty = 威胁检测\n- Inspector = 漏洞评估\n- Macie = 敏感数据发现\n- Security Hub = 聚合与合规态势",
        "domain": "Security and Compliance",
    },
    {
        "id": "M120",
        "question": "关于 CloudWatch vs CloudTrail vs Config 的职责划分，以下哪些说法是正确的？（选择两项）",
        "options": [
            "A. CloudWatch 收集性能指标、日志和告警，关注资源运行状态",
            "B. CloudTrail 记录 AWS API 调用审计日志，回答「谁做了什么」",
            "C. CloudWatch vs CloudTrail vs Config 三者职责完全重叠，可任意互换使用",
            "D. Config 仅用于生成月度成本账单报告，不记录资源配置变更历史",
        ],
        "correct_answers": ["A", "B"],
        "explanation": "正确答案：\n\n「CloudWatch 收集性能指标、日志和告警」\n「CloudTrail 记录 API 调用审计日志」\n\n（Config 记录资源配置变更并评估合规规则。）\n\nCloudWatch vs CloudTrail vs Config 是监控/审计/合规铁三角对比。\n\n错误选项分析：\n\n「三者职责完全重叠可互换」是错误的：CloudWatch 看运行状态，CloudTrail 看 API 操作，Config 看配置变更。\n\n「Config 仅用于成本账单」是错误的：Config 记录资源配置历史并执行合规规则评估。\n\n**重点考点 / 关键词补充：**\n- cloudwatch vs cloudtrail：性能/日志 vs API 审计\n- cloudtrail vs config：操作记录 vs 配置状态\n- 常组合用于安全合规审计",
        "domain": "Security and Compliance",
    },
]